title = "Gitleaks configuration"

[allowlist]
description = "Allow known lab certificate files only"
paths = [
  '''terraform/appgw\.crt''',
  '''terraform/appgw\.key''',
  '''terraform/privkey\.pem''',
  '''terraform/appgw_base64\.txt'''
]