[allowlist]
description = "Allow specific files or paths"
paths = [
    '''terraform/appgw.crt''',
    '''terraform/appgw.key''',
    '''terraform/privkey.pem''',
    '''terraform/appgw_base64.txt'''
]