trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/*
      - azure-pipelines-infra.yml

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDirectory: terraform
  azureServiceConnection: 'sc-project2026'

stages:
- stage: Terraform
  displayName: Terraform Validate Plan Apply
  jobs:
  - job: Terraform_Run
    displayName: Run Terraform
    steps:
    - checkout: self
      clean: true

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform fmt, init, validate, plan, apply
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(terraformWorkingDirectory)
        inlineScript: |
          set -e

          terraform fmt -check
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan