name: Deploy Application

on:
  # workflow_run:
  #   workflows: ["Terraform Infrastructure"]
  #   types:
  #     - completed

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      WEBAPP_NAME: sample-unit-testing-dotnet-mdsr5555-dev
      PUBLISH_PATH: ./publish
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Publish application
        run: dotnet publish PrimeService.Api/PrimeService.Api.csproj --configuration Release --no-build --output ${{ env.PUBLISH_PATH }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.NEWAZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: ${{ env.PUBLISH_PATH }}