name: Terraform Destroy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 1 AM UK (BST)

permissions:
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_application_gateway_ssl_certificate_data: ${{ secrets.APPGW_CERT_DATA }}
      TF_VAR_application_gateway_ssl_certificate_password: ${{ secrets.APPGW_CERT_PASSWORD }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.NEWAZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        run: terraform destroy -var-file="environments/dev.tfvars" -auto-approve